#pragma once

namespace demo
{
enum InputActionIds
{
    INPUT_ACTION_ID_TOGGLE_DEBUG_GUI = 1,

    INPUT_ACTION_ID_QUIT          = 2,
    INPUT_ACTION_ID_ACCEPT        = 3,
    INPUT_ACTION_ID_CANCEL        = 4,

    INPUT_ACTION_ID_MOVE_FORWARD  = 5,
    INPUT_ACTION_ID_MOVE_BACKWARD = 6,
    INPUT_ACTION_ID_MOVE_RIGHT    = 7,
    INPUT_ACTION_ID_MOVE_LEFT     = 8,

    INPUT_ACTION_ID_AIM_HORZ      = 9,
    INPUT_ACTION_ID_AIM_VERT      = 10,
    INPUT_ACTION_ID_FIRE          = 11,

    INPUT_ACTION_ID_TOGGLE_CAMERA = 12,
    INPUT_ACTION_ID_ZOOM_IN       = 13,
    INPUT_ACTION_ID_ZOOM_OUT      = 14,

    INPUT_ACTION_ID_ROTATE_CW     = 15,
    INPUT_ACTION_ID_ROTATE_CCW    = 16,
};
}
